Improve failure

diff --git a/.github/workflows/opensmartmeter.yaml b/.github/workflows/opensmartmeter.yaml
--- a/.github/workflows/opensmartmeter.yaml
+++ b/.github/workflows/opensmartmeter.yaml
@@ -34,11 +34,20 @@ jobs:
       - uses: actions/checkout@v3
       - name: Check URLs in Markdown files
         run: |
+          ERROR_FOUND=false
+
           find . -type f -name "*.md" -exec grep -hEo "(http|https)://[a-zA-Z0-9./?=_%:-]*" {} \; | sort -u | while read -r URL
           do
             STATUS=$(curl -s -o /dev/null -I -w "%{http_code}" "$URL")
-            [ "$STATUS" -ge 400 ] && echo "::error title=HTTP $STATUS::$URL returned $STATUS"
-          done || true
+            if [ "$STATUS" -eq 404 ]; then
+              echo "::error title=HTTP $STATUS::$URL returned $STATUS"
+              ERROR_FOUND=true
+            fi
+          done
+
+          if [ "$ERROR_FOUND" = true ]; then
+            exit 1
+          fi
 
   compile-firmware-platform-io:
     name: Compile Firmware with PlatformIO
